### ISSUE TITLE
Stopped working :(

### ISSUE THREAD

**Issue by logeen** [ArnaudLigny/F-Notifier#62]
Hi,

I have been using this extension for several years. It was working perfectly fine, but a few weeks ago it suddenly stopped. In the extension bar, instead of the number of notifications, I can only see a gray badge with a question mark inside.

Tested on version 2.8.1, Windows 10 and 11, Opera 99 and 100.

**Comment by logeen** [comment]
Tested also on Chrome 115 (newest), Windows 10 - the same issue

**Comment by ArnaudLigny** [comment]
Hello @logeen, there have been no changes on the Facebook side, so the extension should work without problems (regardless of the web browser supported): in general the gray badge with a question mark simply means that the browser is no longer connected to Facebook: can you check? Thx.

**Comment by logeen** [comment]
Hi @ArnaudLigny, thank you for your reply. I tested it on two browsers: Opera and Chrome. Of course I was logged in to Facebook during those tests. Is there other way to connect my browser to Facebook?

**Comment by logeen** [comment]
I can see that F-Notifier extension periodically calls `https://m.facebook.com/` URL address and in response *301 Moved Permanently* is received with location: `https://www.facebook.com/?paipv=...&eav=...&_rdr`

Maybe extension code doesn't follow HTTP redirects? Or maybe it would be more efficient to call directly `https://www.facebook.com/` instead `https://m.facebook.com/` address because this extension is used in desktop browser? Or maybe the fastest way to fix it could be to send some mobile user-agent HTTP header with request to `https://m.facebook.com/`?

**Comment by logeen** [comment]
@ArnaudLigny, please take a look: #63
