### ISSUE TITLE
Can't get F-Notifier to work in Firefox

### ISSUE THREAD

**Issue by piobaire24** [ArnaudLigny/F-Notifier#65]
The icon just shows a "?". Changing various permission settings don't seem to make any difference. It works fine in Chrome, just not Firefox. Any assistance would be appreciated. Thanks :)

**Comment by ArnaudLigny** [comment]
Hello @piobaire24, a new release have been published the last night (#64) on Firefox Add-ons, could you check your version?

![image](https://github.com/ArnaudLigny/F-Notifier/assets/80580/f3ce2cb2-c2d2-4441-805c-60e7f71167b5)

**Comment by piobaire24** [comment]
Hi @ArnaudLigny
Thanks for promptly getting onto this issue. Unfortunately the problem remains.
The F-Notifier icon just shows a question mark

![image](https://github.com/ArnaudLigny/F-Notifier/assets/28533021/3598f4c4-b6f9-4e4c-868f-1337ba378547)

However, clicking the icon does open the relevant Facebook page.

Thanks!
Geoff

**Comment by logeen** [comment]
@piobaire24: could you please paste your Firefox user agent text here? You can check it for example here: https://gs.statcounter.com/detect

**Comment by piobaire24** [comment]
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0

**Comment by piobaire24** [comment]
also... Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0

**Comment by logeen** [comment]
Unfortunately I can't reproduce it :( It works for me with the same user agent. The only way I could have caused this error was to disable cookies completely. But that's not the case, because then you wouldn't be able to log in to Facebook.

Maybe another Firefox browser extension interferes with F-Notifier and causes this error? You can check it by deactivating all extensions except F-Notifier.

**Comment by piobaire24** [comment]
Hi @logeen  - thanks for your reply. Yes, it was another extension preventing F-Notifier from functioning. I disabled the other extension and F-Notifier works fine now. Thanks!
