### ISSUE TITLE
? Mark Remains

### ISSUE THREAD

**Issue by dan073eb** [ArnaudLigny/F-Notifier#66]
My fb notifier version 2.8.3 now has a question mark since yesterday, and notifications do not work.

**Comment by logeen** [comment]
@ArnaudLigny: please, take a look #67

**Comment by ArnaudLigny** [comment]
Thanks a lot @logeen.

Fix tested locally on Chrome, and release 2.8.4 deployed on stores: https://github.com/ArnaudLigny/F-Notifier/actions/runs/7293686048.

**Comment by ArnaudLigny** [comment]
Following: the last version (2.8.4) is available on Chrome and Firefox store.

**Comment by dan073eb** [comment]
Thank you!
